version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cargo-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      bun-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "/infra"
    schedule:
      interval: "weekly"
    groups:
      docker-compose-images:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
