use super::types::{EvidenceSpec, EvidenceValidator};

pub(in crate::operations_evidence) const EVIDENCE_SPECS: &[EvidenceSpec] = &[
    EvidenceSpec {
        name: "operations_preflight",
        file_name: "operations-preflight.json",
        command: "cairn-api operations preflight > operations-preflight.json",
        validator: EvidenceValidator::OperationsPreflight,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "dependency_policy_check",
        file_name: "dependency-policy-check.json",
        command: "cairn-api operations dependency-policy-evidence > dependency-policy-check.json",
        validator: EvidenceValidator::DependencyPolicyCheck,
        contains_secrets: false,
        requires_production_like_environment: false,
        writes_application_state: false,
        touches_external_provider: true,
    },
    EvidenceSpec {
        name: "openid_static_registration",
        file_name: "openid-static-registration.json",
        command: "cairn-api conformance oidcc-static-registration > openid-static-registration.json",
        validator: EvidenceValidator::OpenIdStaticRegistration,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "openid_static_config",
        file_name: "cairn-oidcc-static.json",
        command: "cairn-api conformance oidcc-static-config > cairn-oidcc-static.json",
        validator: EvidenceValidator::OpenIdStaticConfig,
        contains_secrets: true,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "oidc_metadata_smoke",
        file_name: "oidc-metadata-smoke.json",
        command: "cairn-api operations oidc-metadata-smoke > oidc-metadata-smoke.json",
        validator: EvidenceValidator::OidcMetadataSmoke,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "openid_config_op_conformance",
        file_name: "openid-config-op-result.json",
        command: "save OpenID Foundation Config OP suite result JSON as openid-config-op-result.json",
        validator: EvidenceValidator::OpenIdConfigOpConformance,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: true,
    },
    EvidenceSpec {
        name: "openid_basic_op_conformance",
        file_name: "openid-basic-op-result.json",
        command: "save OpenID Foundation Basic OP suite result JSON as openid-basic-op-result.json",
        validator: EvidenceValidator::OpenIdBasicOpConformance,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: true,
    },
    EvidenceSpec {
        name: "scim_generic_connector_profile",
        file_name: "scim-generic-connector-profile.json",
        command: "cairn-api scim connector-profile generic > scim-generic-connector-profile.json",
        validator: EvidenceValidator::ScimGenericConnectorProfile,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "scim_okta_connector_profile",
        file_name: "scim-okta-connector-profile.json",
        command: "cairn-api scim connector-profile okta > scim-okta-connector-profile.json",
        validator: EvidenceValidator::ScimOktaConnectorProfile,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "scim_entra_connector_profile",
        file_name: "scim-entra-connector-profile.json",
        command: "cairn-api scim connector-profile entra > scim-entra-connector-profile.json",
        validator: EvidenceValidator::ScimEntraConnectorProfile,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "scim_public_smoke",
        file_name: "scim-smoke.json",
        command: "cairn-api scim smoke > scim-smoke.json",
        validator: EvidenceValidator::ScimSmoke,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: true,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "scim_okta_connector_smoke",
        file_name: "scim-okta-connector-smoke.json",
        command: "save normalized Okta connector smoke summary as scim-okta-connector-smoke.json",
        validator: EvidenceValidator::ScimOktaConnectorSmoke,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: true,
        touches_external_provider: true,
    },
    EvidenceSpec {
        name: "scim_entra_connector_smoke",
        file_name: "scim-entra-connector-smoke.json",
        command: "save normalized Microsoft Entra connector smoke summary as scim-entra-connector-smoke.json",
        validator: EvidenceValidator::ScimEntraConnectorSmoke,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: true,
        touches_external_provider: true,
    },
    EvidenceSpec {
        name: "browser_origin_smoke",
        file_name: "browser-origin-smoke.json",
        command: "cairn-api operations browser-origin-smoke > browser-origin-smoke.json",
        validator: EvidenceValidator::BrowserOriginSmoke,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "security_headers_smoke",
        file_name: "security-headers-smoke.json",
        command: "cairn-api operations security-headers-smoke > security-headers-smoke.json",
        validator: EvidenceValidator::SecurityHeadersSmoke,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "email_provider_smoke",
        file_name: "email-provider-smoke.json",
        command: "cairn-api email-outbox smoke-provider <recipient-email> > email-provider-smoke.json",
        validator: EvidenceValidator::EmailProviderSmoke,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: true,
    },
    EvidenceSpec {
        name: "lifecycle_email_smoke",
        file_name: "lifecycle-email-smoke.json",
        command: "cairn-api email-outbox lifecycle-smoke-evidence > lifecycle-email-smoke.json",
        validator: EvidenceValidator::LifecycleEmailSmoke,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "restore_drill",
        file_name: "restore-drill.json",
        command: "cairn-api operations restore-check > restore-drill.json",
        validator: EvidenceValidator::RestoreDrill,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "signing_key_rotation_drill",
        file_name: "signing-key-rotation-drill.json",
        command: "cairn-api signing-key rotate > signing-key-rotation-drill.json",
        validator: EvidenceValidator::SigningKeyRotation,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: true,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "kek_rotation_drill",
        file_name: "kek-rotation-drill.json",
        command: "cairn-api key-encryption rotate > kek-rotation-drill.json",
        validator: EvidenceValidator::KeyEncryptionRotation,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: true,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "break_glass_admin_recovery_drill",
        file_name: "break-glass-admin-recovery-drill.json",
        command: "cairn-api admin break-glass-owner <user-email> > break-glass-admin-recovery-drill.json",
        validator: EvidenceValidator::BreakGlassAdminRecovery,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: true,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "audit_export_archive_drill",
        file_name: "audit-export-archive-drill.json",
        command: "cairn-api audit export-ndjson <output-path> > audit-export-archive-drill.json",
        validator: EvidenceValidator::AuditExportArchive,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: false,
        touches_external_provider: false,
    },
    EvidenceSpec {
        name: "audit_retention_purge_drill",
        file_name: "audit-retention-purge-drill.json",
        command: "cairn-api audit purge-expired > audit-retention-purge-drill.json",
        validator: EvidenceValidator::AuditRetentionPurge,
        contains_secrets: false,
        requires_production_like_environment: true,
        writes_application_state: true,
        touches_external_provider: false,
    },
];
